#Arrêt des conteneurs...
docker stop mariadb_vray phpmyadmin_vray wordpress_vray mon-portfolio

#Suppression des conteneurs...
docker rm mariadb_vray phpmyadmin_vray wordpress_vray mon-portfolio

#Suppression des images...
docker rmi mariadb:latest wordpress:latest phpmyadmin:latest portfolio

#Suppression du réseau...
docker network rm sae23_vray